### ISSUE TITLE
El ruben esta muy broken hay que banearlo

### ISSUE THREAD

**Issue by DarkWiiPlayer** [tanoa-life-hentai-etc/administracion#1]
no hay video pero total lo sabe todo el server el ruben come pollas

**Comment by DarkWiiPlayer** [comment]
Propongo:

- [ ] Hechar a ruben
- [x] Cagarse en su madre
- [ ] pegarle una patada en el culo

**Comment by Rubenpaji11** [comment]
dark la chupa
